// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7-5Cf43qeZd72mEoYBL9z9ypfAW7QQUQ',
    appId: '1:47328655837:web:2326c80e493bea7743de34',
    messagingSenderId: '47328655837',
    projectId: 'gocar-b65e2',
    authDomain: 'gocar-b65e2.firebaseapp.com',
    storageBucket: 'gocar-b65e2.appspot.com',
    measurementId: 'G-J50K0W1LZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKOdT3-3_y_gt8R1_HwoZOIhH0QQ9GCaU',
    appId: '1:47328655837:android:46a8450fb364894743de34',
    messagingSenderId: '47328655837',
    projectId: 'gocar-b65e2',
    storageBucket: 'gocar-b65e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd7MRLZP0OHHWlSCTBbVyWVkS8I3m388M',
    appId: '1:47328655837:ios:53b43c21034d41d643de34',
    messagingSenderId: '47328655837',
    projectId: 'gocar-b65e2',
    storageBucket: 'gocar-b65e2.appspot.com',
    iosBundleId: 'com.example.gocar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd7MRLZP0OHHWlSCTBbVyWVkS8I3m388M',
    appId: '1:47328655837:ios:586c6ea6e0d961b243de34',
    messagingSenderId: '47328655837',
    projectId: 'gocar-b65e2',
    storageBucket: 'gocar-b65e2.appspot.com',
    iosBundleId: 'com.example.gocar.RunnerTests',
  );
}
